[KFGunGame.KFGG]
Selection=Long_KFGG_02

[Long_KFGG_01 o_WeaponList]
WarmupTime=30
RemainingTime=900
WeaponList=KFMod.Single
WeaponList=KFMod.MK23Pistol
WeaponList=KFMod.Dual44Magnum
WeaponList=KFMod.Winchester
WeaponList=KFMod.MP5MMedicGun
WeaponList=KFMod.Bullpup
WeaponList=KFMod.Crossbow
WeaponList=KFMod.M7A3MMedicGun
WeaponList=KFMod.FlameThrower
WeaponList=KFMod.M4AssaultRifle
WeaponList=KFMod.AK47AssaultRifle
WeaponList=KFMod.BoomStick
WeaponList=KFMod.M14EBRBattleRifle
WeaponList=KFMod.DualDeagle
WeaponList=KFMod.BenelliShotgun
WeaponList=KFGunGame.GG_M79GrenadeLauncher
WeaponList=KFMod.FNFAL_ACOG_AssaultRifle
WeaponList=KFGunGame.GG_M32GrenadeLauncher
WeaponList=KFMod.M99SniperRifle
WeaponList=KFMod.AA12AutoShotgun
WeaponList=KFGunGame.GG_LAW
WeaponList=KFMod.Katana

[Long_KFGG_02 o_WeaponList]
WarmupTime=30
RemainingTime=960
TeamChars=(Red="Sergeant_Powers;Corporal_Lewis;Lieutenant_Masterson;Trooper_Clive_Jenkins;LanceCorporal_Lee_Baron;Private_Schnieder",Blue="Police_Constable_Briar;Police_Sergeant_Davin;Paramedic_Alfred_Anderson")
WeaponList=KFMod.Single
WeaponList=KFMod.MK23Pistol
WeaponList=KFMod.Dualies
WeaponList=KFMod.DualMK23Pistol
WeaponList=KFMod.Magnum44Pistol
WeaponList=KFMod.Dual44Magnum
; WeaponList=KFMod.FlareRevolver
WeaponList=KFMod.Winchester
WeaponList=KFMod.MAC10MP
WeaponList=KFMod.MP7MMedicGun
WeaponList=KFMod.MP5MMedicGun
WeaponList=KFMod.Bullpup
WeaponList=KFmod.ThompsonSMG
WeaponList=KFMod.Crossbow
WeaponList=KFMod.Crossbuzzsaw
WeaponList=KFMod.Shotgun
WeaponList=KFMod.SPSniperRifle
WeaponList=KFMod.M7A3MMedicGun
WeaponList=KFMod.KrissMMedicGun
WeaponList=KFMod.NailGun
WeaponList=KFMod.FlameThrower
WeaponList=KFMod.Deagle
WeaponList=KFMod.M4AssaultRifle
WeaponList=KFMod.KSGShotgun
WeaponList=KFMod.AK47AssaultRifle
WeaponList=KFMod.MKb42AssaultRifle
WeaponList=KFMod.BoomStick
WeaponList=KFMod.SPThompsonSMG
WeaponList=KFMod.Trenchgun
WeaponList=KFMod.M14EBRBattleRifle
WeaponList=KFMod.SPAutoShotgun
WeaponList=KFMod.DualDeagle
WeaponList=KFMod.ThompsonDrumSMG
WeaponList=KFMod.SeekerSixRocketLauncher
WeaponList=KFMod.SealSquealHarpoonBomber
WeaponList=KFMod.BenelliShotgun
WeaponList=KFMod.ZEDGun
WeaponList=KFGunGame.GG_M79GrenadeLauncher
WeaponList=KFMod.SCARMK17AssaultRifle
WeaponList=KFMod.SPGrenadeLauncher
WeaponList=KFMod.ZEDMKIIWeapon
WeaponList=KFMod.FNFAL_ACOG_AssaultRifle
WeaponList=KFGunGame.GG_M4203AssaultRifle
WeaponList=KFGunGame.GG_M32GrenadeLauncher
WeaponList=KFMod.M99SniperRifle
WeaponList=KFGunGame.GG_HuskGun
WeaponList=KFMod.AA12AutoShotgun
WeaponList=KFGunGame.GG_LAW
WeaponList=KFMod.BlowerThrower
WeaponList=KFMod.DwarfAxe

[Short_KFGG_01 o_WeaponList]
WarmupTime=30
RemainingTime=900
WeaponList=KFMod.Single
WeaponList=KFMod.MK23Pistol
WeaponList=KFMod.Dual44Magnum
WeaponList=KFMod.Winchester
WeaponList=KFMod.MP5MMedicGun
WeaponList=KFMod.Bullpup
WeaponList=KFMod.Crossbow
WeaponList=KFMod.M7A3MMedicGun
WeaponList=KFMod.FlameThrower
WeaponList=KFMod.M4AssaultRifle
WeaponList=KFMod.AK47AssaultRifle
WeaponList=KFMod.BoomStick
WeaponList=KFMod.M14EBRBattleRifle
WeaponList=KFMod.DualDeagle
WeaponList=KFMod.BenelliShotgun
WeaponList=KFGunGame.GG_M79GrenadeLauncher
WeaponList=KFMod.FNFAL_ACOG_AssaultRifle
WeaponList=KFGunGame.GG_M32GrenadeLauncher
WeaponList=KFMod.M99SniperRifle
WeaponList=KFMod.AA12AutoShotgun
WeaponList=KFGunGame.GG_LAW
WeaponList=KFMod.Katana

[Short_KFGG_02 o_WeaponList]
WarmupTime=30
RemainingTime=900
WeaponList=KFMod.Single
WeaponList=KFMod.MK23Pistol
WeaponList=KFMod.Dualies
WeaponList=KFMod.DualMK23Pistol
WeaponList=KFMod.Magnum44Pistol
WeaponList=KFMod.Dual44Magnum
WeaponList=KFMod.Winchester
WeaponList=KFMod.MAC10MP
WeaponList=KFMod.MP7MMedicGun
WeaponList=KFMod.MP5MMedicGun
WeaponList=KFMod.Bullpup
WeaponList=KFMod.Crossbow
WeaponList=KFMod.Shotgun
WeaponList=KFMod.M7A3MMedicGun
WeaponList=KFMod.FlameThrower
WeaponList=KFMod.Deagle
WeaponList=KFMod.M4AssaultRifle
WeaponList=KFMod.KSGShotgun
WeaponList=KFMod.AK47AssaultRifle
WeaponList=KFMod.BoomStick
WeaponList=KFMod.M14EBRBattleRifle
WeaponList=KFMod.DualDeagle
WeaponList=KFMod.BenelliShotgun
WeaponList=KFGunGame.GG_M79GrenadeLauncher
WeaponList=KFMod.SCARMK17AssaultRifle
WeaponList=KFMod.FNFAL_ACOG_AssaultRifle
WeaponList=KFGunGame.GG_M4203AssaultRifle
WeaponList=KFGunGame.GG_M32GrenadeLauncher
WeaponList=KFMod.M99SniperRifle
WeaponList=KFGunGame.GG_HuskGun
WeaponList=KFMod.AA12AutoShotgun
WeaponList=KFGunGame.GG_LAW
WeaponList=KFMod.Katana

[iSnipe_01 o_WeaponList]
WarmupTime=30
RemainingTime=900
WeaponList=KFGunGame.GG_M99SniperRifle
WeaponList=KFGunGame.GG_M99SniperRifle
WeaponList=KFGunGame.GG_M99SniperRifle
WeaponList=KFGunGame.GG_M99SniperRifle
WeaponList=KFGunGame.GG_M99SniperRifle
WeaponList=KFGunGame.GG_M99SniperRifle

[iSnipe_02 o_WeaponList]
WarmupTime=30
RemainingTime=900
WeaponList=KFGunGame.GG_M99SniperRifle
WeaponList=KFGunGame.GG_M99SniperRifle
WeaponList=KFGunGame.GG_M99SniperRifle
WeaponList=KFGunGame.GG_M99SniperRifle
WeaponList=KFGunGame.GG_M99SniperRifle
WeaponList=KFGunGame.GG_M99SniperRifle
WeaponList=KFGunGame.GG_M99SniperRifle
WeaponList=KFGunGame.GG_M99SniperRifle
WeaponList=KFGunGame.GG_M99SniperRifle
WeaponList=KFGunGame.GG_M99SniperRifle
WeaponList=KFGunGame.GG_M99SniperRifle
WeaponList=KFGunGame.GG_M99SniperRifle
WeaponList=KFGunGame.GG_M99SniperRifle
WeaponList=KFGunGame.GG_M99SniperRifle
WeaponList=KFGunGame.GG_M99SniperRifle
WeaponList=KFGunGame.GG_M99SniperRifle
